# pull official base image
FROM mongo:latest

# Set local timezone.
ENV TZ=Asia/Baku
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# COPY ./check_mongodb.sh .
# RUN ["chmod", "+x", "/check_mongodb.sh"]
# ENTRYPOINT ["/check_mongodb.sh"] 